---
abstract: 'base class for Metabase Facts'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Metabase-Fact
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Metabase::Fact:
    file: lib/Metabase/Fact.pm
    version: 0.009
  Metabase::Fact::Hash:
    file: lib/Metabase/Fact/Hash.pm
    version: 0.009
  Metabase::Fact::String:
    file: lib/Metabase/Fact/String.pm
    version: 0.009
  Metabase::Report:
    file: lib/Metabase/Report.pm
    version: 0.009
  Metabase::Resource:
    file: lib/Metabase/Resource.pm
    version: 0.009
  Metabase::Resource::cpan:
    file: lib/Metabase/Resource/cpan.pm
    version: 0.009
  Metabase::Resource::cpan::distfile:
    file: lib/Metabase/Resource/cpan/distfile.pm
    version: 0.009
  Metabase::Resource::metabase:
    file: lib/Metabase/Resource/metabase.pm
    version: 0.009
  Metabase::Resource::metabase::fact:
    file: lib/Metabase/Resource/metabase/fact.pm
    version: 0.009
  Metabase::Resource::metabase::user:
    file: lib/Metabase/Resource/metabase/user.pm
    version: 0.009
  Metabase::User::EmailAddress:
    file: lib/Metabase/User/EmailAddress.pm
    version: 0.009
  Metabase::User::FullName:
    file: lib/Metabase/User/FullName.pm
    version: 0.009
  Metabase::User::Profile:
    file: lib/Metabase/User/Profile.pm
    version: 0.009
  Metabase::User::Secret:
    file: lib/Metabase/User/Secret.pm
    version: 0.009
requires:
  CPAN::DistnameInfo: 0
  Carp: 0
  Cwd: 0
  Data::GUID: 0
  File::Find: 0
  File::Spec: 3
  File::Temp: 0.20
  JSON: 2
  Test::Exception: 0
  Test::More: 0.88
  perl: 5.006
resources:
  repository: http://github.com/dagolden/metabase-fact
version: 0.009
