---
abstract: 'base class for Metabase Facts'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'H.Merijn Brand <hmbrand@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Metabase-Fact
no_index:
  directory:
    - t
    - xt
    - examples
recommends: {}
requires:
  CPAN::DistnameInfo: 0
  Carp: 0
  Cwd: 0
  Data::GUID: 0
  File::Find: 0
  File::Spec: 3
  File::Temp: 0.20
  JSON: 2
  Test::Exception: 0
  Test::More: 0.88
  perl: 5.006
resources:
  repository: http://github.com/dagolden/metabase-fact
version: 0.012
