use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
David
Golden
dagolden
Ricardo
Signes
rjbs
Merijn
Brand
hmbrand
Nathan
Gary
Glenn
nglenn
Randy
Stauner
rwstauner
lib
Metabase
Resource
cpan
distfile
perl
Report
User
EmailAddress
metabase
fact
user
Profile
Fact
String
FullName
commit
Hash
Secret
