use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
David
Golden
dagolden
Ricardo
Signes
rjbs
Merijn
Brand
hmbrand
Steinbrunner
dsteinbrunner
Karen
Etheridge
ether
Nathan
Gary
Glenn
nglenn
Randy
Stauner
rwstauner
lib
Metabase
User
Profile
FullName
Fact
Resource
metabase
user
Secret
cpan
fact
Report
perl
commit
String
distfile
Hash
EmailAddress
