use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
analyses
cpan
datatype
distfile
guid
identifier
json
metabase
subtype
uri's
utc
David
Golden
dagolden
Ricardo
Signes
rjbs
Merijn
Brand
hmbrand
Nathan
Gary
Glenn
nglenn
Randy
Stauner
rwstauner
lib
Metabase
Resource
fact
User
FullName
EmailAddress
perl
commit
Report
Profile
Fact
String
Secret
user
Hash
